# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blog',
                'doc_host': 'https://infinitelylearn.github.io',
                'git_url': 'https://github.com/infinitelylearn/blog',
                'lib_path': 'blog'},
  'syms': { 'blog.blog': {'blog.blog.foo': ('posts/2024-09-05-my-journey-into-deep-learning-and-beyond/index.html#foo', 'blog/blog.py')},
            'blog.core': {'blog.core.foo': ('posts/2024-09-04-intro/index.html#foo', 'blog/core.py')}}}
