"""From Techno to Tensorflow"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/posts/2024-09-05-my-journey-into-deep-learning-and-beyond/index.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/posts/2024-09-05-my-journey-into-deep-learning-and-beyond/index.ipynb 11
def foo(): pass
