"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/blog/posts/2024-09-04-test/index.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/blog/posts/2024-09-04-test/index.ipynb 3
def foo(): pass
