"""This is my first actual test post"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/posts/2024-09-04-test/index.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../nbs/posts/2024-09-04-test/index.ipynb 5
def foo(): pass
