"""Page description"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Test.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/Test.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/Test.ipynb 4
def foo(): pass
