project:
  type: website

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 4
    keep-md: true
  commonmark: default
  
website:
  title: "Infinitely Learn"
  site-url: https://infinitelylearn.github.io/blog
  description: "my journey Deep learning, Machine learning, Reinforcement Learning, and any other type of learning"
  image: "/images/tris-card.jpg"
  description: "an AI researcher going back to school for immunology"
  creator: "@infinitelylearn"
  site: "@infinitelylearn"
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: twitter
        href: https://twitter.com/math_rachel
      - icon: linkedin
        href: https://www.linkedin.com/in/rachel-thomas-942a7923/
      - icon: youtube
        href: https://www.youtube.com/playlist?list=PLtmWHNX-gukLQlMvtRJ19s7-8MrnRV6h6
      - icon: rss
        href: index.xml
      - text: Archive
        href: archive.qmd  
        
metadata-files: [nbdev.yml, sidebar.yml]