project:
  type: website

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    toc-depth: 4
    keep-md: true
  commonmark: default

website:
  title: "Infinitely Learn"
  site-url: https://infinitelylearn.com
  description: "My journey into Deep Learning, Machine Learning, Reinforcement Learning, and any other type of learning"
  image: "/images/tris-card.jpg"
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - icon: twitter
        href: https://twitter.com/infinitelylearn
      - text: Archive
        href: archive.qmd  

resources:
  - CNAME

metadata-files: [nbdev.yml]