name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Copy CNAME file
        run: |
          # Make sure to place the CNAME in the correct location before deployment
          echo "infinitelylearn.com" > CNAME  # Create or overwrite the CNAME file
      - uses: fastai/workflows/quarto-ghp@master
        with:
          target_branch: gh-pages  # Ensure this matches your deployment branch
          keep_files: true         # Optional: keeps existing files, ensuring CNAME isn't removed
